<a href="https://colab.research.google.com/github/kayari89/REDES-NEURONALES/blob/main/libreias_escikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
# 2️⃣ Cargar el conjunto de datos de Iris
iris = load_iris()
X, y = iris.data, iris.target

import pandas as pd

# Convertir los datos a una tabla (DataFrame)
df = pd.DataFrame(X, columns=iris.feature_names)

# Agregar la columna de la especie
df["species"] = y

# Mostrar las primeras filas de la tabla
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# (Opcional) Explorando el conjunto de datos
type(iris)
iris.keys()
iris['data']
iris['target']
iris['target_names']
iris['DESCR']
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
# 3️⃣ Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# 4️⃣ Escalar las características para un mejor rendimiento del modelo
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# 5️⃣ Crear una instancia de MLPClassifier
mlp_clf = MLPClassifier(hidden_layer_sizes=(100),
    activation='relu',
    solver='adam',
    max_iter=100,
    random_state=42,
    verbose=True
)

In [ ]:
#  Entrenar el modelo
mlp_clf.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.16374923
Iteration 2, loss = 1.14090611
Iteration 3, loss = 1.11857816
Iteration 4, loss = 1.09677375
Iteration 5, loss = 1.07547149
Iteration 6, loss = 1.05468504
Iteration 7, loss = 1.03440573
Iteration 8, loss = 1.01462373
Iteration 9, loss = 0.99535820
Iteration 10, loss = 0.97658926
Iteration 11, loss = 0.95833257
Iteration 12, loss = 0.94053852
Iteration 13, loss = 0.92322169
Iteration 14, loss = 0.90638373
Iteration 15, loss = 0.89000670
Iteration 16, loss = 0.87408395
Iteration 17, loss = 0.85861030
Iteration 18, loss = 0.84357120
Iteration 19, loss = 0.82895431
Iteration 20, loss = 0.81476466
Iteration 21, loss = 0.80097410
Iteration 22, loss = 0.78759157
Iteration 23, loss = 0.77460302
Iteration 24, loss = 0.76199129
Iteration 25, loss = 0.74975377
Iteration 26, loss = 0.73786826
Iteration 27, loss = 0.72632581
Iteration 28, loss = 0.71511871
Iteration 29, loss = 0.70424319
Iteration 30, loss = 0.69368183
Iteration 31, loss = 0.68342580
Iteration 32, loss = 0.67346953
Iteration 33, loss = 0.66380608
Iteration 34, loss = 0.65442161
Iteration 35, loss = 0.64531278
Iteration 36, loss = 0.63647902
Iteration 37, loss = 0.62790342
Iteration 38, loss = 0.61957863
Iteration 39, loss = 0.61148527
Iteration 40, loss = 0.60361466
Iteration 41, loss = 0.59597076
Iteration 42, loss = 0.58855743
Iteration 43, loss = 0.58136358
Iteration 44, loss = 0.57437150
Iteration 45, loss = 0.56758016
Iteration 46, loss = 0.56097952
Iteration 47, loss = 0.55455113
Iteration 48, loss = 0.54829175
Iteration 49, loss = 0.54219766
Iteration 50, loss = 0.53626159
Iteration 51, loss = 0.53048210
Iteration 52, loss = 0.52484566
Iteration 53, loss = 0.51933866
Iteration 54, loss = 0.51394846
Iteration 55, loss = 0.50869354
Iteration 56, loss = 0.50356710
Iteration 57, loss = 0.49857160
Iteration 58, loss = 0.49370008
Iteration 59, loss = 0.48894487
Iteration 60, loss = 0.48429908
Iteration 61, loss = 0.47974886
Iteration 62, loss = 0.47529331
Iteration 63, loss = 0.47093384
Iteration 64, loss = 0.46667067
Iteration 65, loss = 0.46249978
Iteration 66, loss = 0.45841914
Iteration 67, loss = 0.45442291
Iteration 68, loss = 0.45050855
Iteration 69, loss = 0.44667746
Iteration 70, loss = 0.44292801
Iteration 71, loss = 0.43926405
Iteration 72, loss = 0.43567120
Iteration 73, loss = 0.43215951
Iteration 74, loss = 0.42871948
Iteration 75, loss = 0.42534205
Iteration 76, loss = 0.42201917
Iteration 77, loss = 0.41875279
Iteration 78, loss = 0.41554234
Iteration 79, loss = 0.41238463
Iteration 80, loss = 0.40928512
Iteration 81, loss = 0.40623752
Iteration 82, loss = 0.40323632
Iteration 83, loss = 0.40027444
Iteration 84, loss = 0.39735268
Iteration 85, loss = 0.39447038
Iteration 86, loss = 0.39162936
Iteration 87, loss = 0.38882549
Iteration 88, loss = 0.38605547
Iteration 89, loss = 0.38331954
Iteration 90, loss = 0.38062197
Iteration 91, loss = 0.37796519
Iteration 92, loss = 0.37534717
Iteration 93, loss = 0.37276083
Iteration 94, loss = 0.37020149
Iteration 95, loss = 0.36766960
Iteration 96, loss = 0.36516474
Iteration 97, loss = 0.36267665
Iteration 98, loss = 0.36021595
Iteration 99, loss = 0.35777846
Iteration 100, loss = 0.35536449

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=100, max_iter=100, random_state=42,
              verbose=True)

In [ ]:
# 7️⃣ Realizar predicciones en el conjunto de prueba
y_pred = mlp_clf.predict(X_test_scaled)

print(y_test)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

In [ ]:
# 8️⃣ Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo:", accuracy)

Precisión del modelo: 0.9333333333333333

In [ ]:
# 1️⃣ Cargar las librerías necesarias
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [ ]:
# 2️⃣ Cargar el conjunto de datos de California Housing
housing = fetch_california_housing()

X, y = housing.data, housing.target

In [ ]:
import pandas as pd

# Crear un DataFrame con los datos de California Housing
df_housing = pd.DataFrame(housing.data, columns=housing.feature_names)

# Añadir la variable objetivo
df_housing['MedHouseVal'] = housing.target

# Mostrar las primeras filas de la tabla
display(df_housing.head())

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
# 🔎 Explorando los datos (Opcional)
type(housing)
housing.keys()
housing['data']
housing['target']
housing['target_names']
housing['DESCR']
housing['feature_names']

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

### Explicación de las Columnas del Conjunto de Datos California Housing

Las columnas en el conjunto de datos de California Housing representan diversas características de los distritos censales de California. Aquí su significado:

*   **MedInc (Median Income):** Ingreso mediano por hogar en el distrito (en decenas de miles de dólares estadounidenses).
*   **HouseAge (Median House Age):** Edad mediana de las casas en el distrito.
*   **AveRooms (Average Number of Rooms):** Número promedio de habitaciones por vivienda en el distrito.
*   **AveBedrms (Average Number of Bedrooms):** Número promedio de dormitorios por vivienda en el distrito.
*   **Population (Block Population):** Población total del distrito censal.
*   **AveOccup (Average Occupancy):** Ocupación promedio de los hogares en el distrito (número de personas por hogar).
*   **Latitude (Latitude):** Latitud del distrito censal.
*   **Longitude (Longitude):** Longitud del distrito censal.
*   **MedHouseVal (Median House Value):** Valor mediano de la vivienda en el distrito (la variable objetivo, en cientos de miles de dólares estadounidenses).

In [ ]:
# 3️⃣ Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# 4️⃣ Escalar las características para un mejor rendimiento del modelo
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# 5️⃣ Crear una instancia de MLPRegressor
mlp_reg = MLPRegressor(
    hidden_layer_sizes=(100,),
    activation='relu',
    solver='adam',
    max_iter=100,
    random_state=42,
    verbose=True
)

In [ ]:
# 6️⃣ Entrenar el modelo
mlp_reg.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.62056447
Iteration 2, loss = 0.43678846
Iteration 3, loss = 0.32700527
Iteration 4, loss = 0.28069940
Iteration 5, loss = 0.24814135
Iteration 6, loss = 0.22803342
Iteration 7, loss = 0.21538976
Iteration 8, loss = 0.20787968
Iteration 9, loss = 0.20154389
Iteration 10, loss = 0.19743378
Iteration 11, loss = 0.19321222
Iteration 12, loss = 0.18961729
Iteration 13, loss = 0.18678600
Iteration 14, loss = 0.18383630
Iteration 15, loss = 0.18157601
Iteration 16, loss = 0.17968086
Iteration 17, loss = 0.17775103
Iteration 18, loss = 0.17538371
Iteration 19, loss = 0.17423819
Iteration 20, loss = 0.17407294
Iteration 21, loss = 0.17085613
Iteration 22, loss = 0.16995187
Iteration 23, loss = 0.16823352
Iteration 24, loss = 0.16798530
Iteration 25, loss = 0.16717835
Iteration 26, loss = 0.16566984
Iteration 27, loss = 0.16730781
Iteration 28, loss = 0.16499618
Iteration 29, loss = 0.16261953
Iteration 30, loss = 0.16145474
Iteration 31, loss = 0.16053131
Iteration 32, loss = 0.16002333
Iteration 33, loss = 0.16125255
Iteration 34, loss = 0.15863582
Iteration 35, loss = 0.15835131
Iteration 36, loss = 0.15795060
Iteration 37, loss = 0.15703766
Iteration 38, loss = 0.15707574
Iteration 39, loss = 0.15768516
Iteration 40, loss = 0.15525691
Iteration 41, loss = 0.15632172
Iteration 42, loss = 0.15467901
Iteration 43, loss = 0.15438915
Iteration 44, loss = 0.15556876
Iteration 45, loss = 0.15329744
Iteration 46, loss = 0.15273177
Iteration 47, loss = 0.15307344
Iteration 48, loss = 0.15369159
Iteration 49, loss = 0.15240098
Iteration 50, loss = 0.15143071
Iteration 51, loss = 0.15112755
Iteration 52, loss = 0.15083169
Iteration 53, loss = 0.15061975
Iteration 54, loss = 0.17536085
Iteration 55, loss = 0.15573187
Iteration 56, loss = 0.15049969
Iteration 57, loss = 0.14988656
Iteration 58, loss = 0.15022315
Iteration 59, loss = 0.14961153
Iteration 60, loss = 0.14848394
Iteration 61, loss = 0.14950369
Iteration 62, loss = 0.14843954
Iteration 63, loss = 0.14811978
Iteration 64, loss = 0.14766317
Iteration 65, loss = 0.14793107
Iteration 66, loss = 0.14733359
Iteration 67, loss = 0.14800560
Iteration 68, loss = 0.14665149
Iteration 69, loss = 0.14686777
Iteration 70, loss = 0.14665771
Iteration 71, loss = 0.14612037
Iteration 72, loss = 0.14639346
Iteration 73, loss = 0.14671723
Iteration 74, loss = 0.14576906
Iteration 75, loss = 0.15060883
Iteration 76, loss = 0.14555955
Iteration 77, loss = 0.14514246
Iteration 78, loss = 0.14553115
Iteration 79, loss = 0.14643439
Iteration 80, loss = 0.14501085
Iteration 81, loss = 0.14468993
Iteration 82, loss = 0.14489975
Iteration 83, loss = 0.14516740
Iteration 84, loss = 0.14435448
Iteration 85, loss = 0.14397719
Iteration 86, loss = 0.14633622
Iteration 87, loss = 0.14389402
Iteration 88, loss = 0.14379916
Iteration 89, loss = 0.14337806
Iteration 90, loss = 0.14402555
Iteration 91, loss = 0.14472118
Iteration 92, loss = 0.14661691
Iteration 93, loss = 0.15462744
Iteration 94, loss = 0.14386535
Iteration 95, loss = 0.14275879
Iteration 96, loss = 0.14295641
Iteration 97, loss = 0.14219076
Iteration 98, loss = 0.14180756
Iteration 99, loss = 0.14206889
Iteration 100, loss = 0.14286992

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPRegressor(max_iter=100, random_state=42, verbose=True)